import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from "docx";
import { MangaPageItem, TagRule } from "@/types/manga";
import { extractPageNumber } from "@/lib/zipUtils";
import { formatTextWithRules } from "@/lib/exportUtils";

export interface DocxExportOptions {
  startPageNumber?: number;
  useFilenamePageNumber?: boolean;
  tags?: TagRule[];
  tagsEnabled?: boolean;
  textType?: "original" | "translated";
  extractSFX?: boolean;
}

export function createChapterDocxDocument(
  pages: MangaPageItem[],
  isRTL: boolean = true,
  options?: DocxExportOptions,
): Document {
  const docChildren: Paragraph[] = [];

  // Title Document Heading
  docChildren.push(
    new Paragraph({
      text: "MANGA TYPER TRANSLATION SCRIPT",
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      spacing: { after: 120, before: 100 },
    }),
  );

  docChildren.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `Total Pages: ${pages.length} | Generated by Manga Typer Studio AI`,
          italics: true,
          color: "666666",
          size: 20, // 10pt
        }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { after: 300 },
    }),
  );

  // Iterate each page and add headings + paragraphs
  pages.forEach((page, pageIndex) => {
    let pageNum = (options?.startPageNumber || 1) + pageIndex;
    if (options?.useFilenamePageNumber !== false) {
      const detected = extractPageNumber(page.fileName);
      if (detected !== null && detected > 0) {
        pageNum = detected;
      }
    }

    // Page Section Header
    docChildren.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `------------------------------------------------------`,
            color: "DD6B20",
          }),
        ],
        spacing: { before: 200 },
      }),
    );

    docChildren.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `PAGE #${pageNum}: ${page.fileName}`,
            bold: true,
            size: 24, // 12pt
            color: "DD6B20",
          }),
        ],
        heading: HeadingLevel.HEADING_2,
        alignment: isRTL ? AlignmentType.RIGHT : AlignmentType.LEFT,
        bidirectional: isRTL,
        spacing: { before: 80, after: 120 },
      }),
    );

    if (!page.items || page.items.length === 0) {
      docChildren.push(
        new Paragraph({
          children: [
            new TextRun({
              text: "// No dialogue or text detected on this page",
              italics: true,
              color: "999999",
            }),
          ],
          alignment: isRTL ? AlignmentType.RIGHT : AlignmentType.LEFT,
          bidirectional: isRTL,
          spacing: { after: 160 },
        }),
      );
      return;
    }

    page.items.forEach((item) => {
      if (
        options?.extractSFX === false &&
        (item.category === "sfx" || item.category?.toLowerCase() === "sfx")
      ) {
        return;
      }
      const rawText = options?.textType === "original" ? item.originalText : item.translatedText;
      const formattedText = formatTextWithRules(
        rawText,
        item.category,
        options?.tags || [],
        options?.tagsEnabled !== false,
      );
      if (!formattedText.trim()) return;

      docChildren.push(
        new Paragraph({
          children: [
            new TextRun({
              text: formattedText,
              size: 24, // 12pt
              font: isRTL ? "Traditional Arabic" : "Calibri",
            }),
          ],
          alignment: isRTL ? AlignmentType.RIGHT : AlignmentType.LEFT,
          bidirectional: isRTL,
          spacing: { after: 80 },
        }),
      );
    });

    // Space after page block
    docChildren.push(
      new Paragraph({
        text: "",
        spacing: { after: 160 },
      }),
    );
  });

  return new Document({
    sections: [
      {
        properties: {},
        children: docChildren,
      },
    ],
  });
}

export async function exportChapterToDocx(
  pages: MangaPageItem[],
  isRTL: boolean = true,
  options?: DocxExportOptions,
  customFileName?: string,
): Promise<void> {
  const doc = createChapterDocxDocument(pages, isRTL, options);
  const blob = await Packer.toBlob(doc);
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = customFileName || `Manga_Chapter_Typer_${Date.now()}.docx`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
