import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from "docx";
import { MangaPageItem } from "@/types/manga";

export async function exportChapterToDocx(pages: MangaPageItem[], isRTL: boolean = true): Promise<void> {
  const docChildren: Paragraph[] = [];

  // Title Document Heading
  docChildren.push(
    new Paragraph({
      text: "MANGA TYPER TRANSLATION SCRIPT",
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      spacing: { after: 120, before: 100 },
    })
  );

  docChildren.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `Total Pages: ${pages.length} | Generated by Manga Typer Studio AI`,
          italics: true,
          color: "666666",
          size: 20, // 10pt
        }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { after: 300 },
    })
  );

  // Iterate each page and add headings + paragraphs
  pages.forEach((page, pageIndex) => {
    const pageNum = pageIndex + 1;

    // Page Section Header
    docChildren.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `------------------------------------------------------`,
            color: "DD6B20",
          }),
        ],
        spacing: { before: 200 },
      })
    );

    docChildren.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `PAGE #${pageNum}: ${page.fileName}`,
            bold: true,
            size: 24, // 12pt
            color: "DD6B20",
          }),
        ],
        heading: HeadingLevel.HEADING_2,
        alignment: isRTL ? AlignmentType.RIGHT : AlignmentType.LEFT,
        bidirectional: isRTL,
        spacing: { before: 80, after: 120 },
      })
    );

    if (!page.items || page.items.length === 0) {
      docChildren.push(
        new Paragraph({
          children: [
            new TextRun({
              text: "// No dialogue or text detected on this page",
              italics: true,
              color: "999999",
            }),
          ],
          alignment: isRTL ? AlignmentType.RIGHT : AlignmentType.LEFT,
          bidirectional: isRTL,
          spacing: { after: 160 },
        })
      );
      return;
    }

    page.items.forEach((item) => {
      const formattedText = item.translatedText.trim();
      docChildren.push(
        new Paragraph({
          children: [
            new TextRun({
              text: formattedText,
              size: 24, // 12pt
              font: isRTL ? "Traditional Arabic" : "Calibri",
            }),
          ],
          alignment: isRTL ? AlignmentType.RIGHT : AlignmentType.LEFT,
          bidirectional: isRTL,
          spacing: { after: 80 },
        })
      );
    });

    // Space after page block
    docChildren.push(
      new Paragraph({
        text: "",
        spacing: { after: 160 },
      })
    );
  });

  const doc = new Document({
    sections: [
      {
        properties: {},
        children: docChildren,
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `Manga_Chapter_Typer_${Date.now()}.docx`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}